-- ============================================================================
-- Vcore — Carga del catálogo base (26 productos)
-- Pegá TODO esto en: Supabase -> SQL Editor -> New query -> Run
-- Idempotente: si un producto ya existe, lo actualiza (no duplica).
-- ============================================================================
insert into public.products
  (id, name, sub, category, badge, blurb, tone, photo, variants, price, rating, reviews, visible, featured, sort)
values
  ('creatina', 'Creatina', 'Monohidrato', 'Rendimiento', 'Más vendido', 'Energía celular, claridad mental y rendimiento para tu rutina diaria. Sin vueltas.', 'paper', '/assets/product-creatina-locker.jpg', '[{"label":"300 gr","price":14990},{"label":"500 gr","price":14990}]'::jsonb, 14990, 4.9, 312, true, true, 0),
  ('proteina', 'Proteína', 'Aislado de Suero de Leche', 'Recuperación', '', 'Recuperación y construcción muscular con proteína de alta absorción.', 'green', '', '[{"label":"1 kg","price":28990},{"label":"2 kg","price":28990}]'::jsonb, 28990, 4.8, 198, true, true, 1),
  ('magnesio', 'Magnesio', 'Bisglicinato', 'Recuperación', '', 'Descanso, recuperación y función muscular para cerrar bien el día.', 'sage', '', '[{"label":"120 caps","price":11990}]'::jsonb, 11990, 4.9, 87, true, true, 2),
  ('vitamina-c', 'Vitamina C', 'Ascorbato puro — Cápsulas', 'Vitaminas', '', 'Antioxidante esencial. Apoyo inmunológico y síntesis de colágeno sin excipientes.', 'green', '', '[{"label":"60 caps","price":11400},{"label":"120 caps","price":11400}]'::jsonb, 11400, 4.8, 54, true, false, 3),
  ('vitamina-c-polvo', 'Vitamina C', 'Ascorbato puro — Polvo', 'Vitaminas', '', 'Vitamina C en polvo de alta pureza. Dosificación flexible, sin excipientes.', 'green', '', '[{"label":"100 gr","price":7300},{"label":"250 gr","price":7300}]'::jsonb, 7300, 4.8, 31, true, false, 4),
  ('triple-mag', 'Triple Magnesio', 'Citrato · Glicinato · Malato — Cápsulas', 'Vitaminas', '', 'Tres formas de magnesio en una cápsula. Máxima absorción y biodisponibilidad.', 'sage', '', '[{"label":"90 caps","price":16500},{"label":"180 caps","price":16500}]'::jsonb, 16500, 4.9, 41, true, false, 5),
  ('triple-mag-polvo', 'Triple Magnesio', 'Citrato · Glicinato · Malato — Polvo', 'Vitaminas', '', 'Triple magnesio en polvo. Dosificación precisa, sin cápsulas.', 'sage', '', '[{"label":"150 gr","price":15000},{"label":"300 gr","price":15000}]'::jsonb, 15000, 4.8, 19, true, false, 6),
  ('citrato-magnesio', 'Citrato de Magnesio', 'Cápsulas', 'Vitaminas', '', 'Alta absorción y tolerancia digestiva. Forma clásica y bien estudiada.', 'sage', '', '[{"label":"60 caps","price":14000},{"label":"120 caps","price":14000}]'::jsonb, 14000, 4.8, 33, true, false, 7),
  ('citrato-magnesio-polvo', 'Citrato de Magnesio', 'Polvo', 'Vitaminas', '', 'Citrato de magnesio en polvo. Disolvé en agua o jugo, sin sabor agregado.', 'sage', '', '[{"label":"150 gr","price":7000},{"label":"300 gr","price":7000}]'::jsonb, 7000, 4.8, 22, true, false, 8),
  ('glicinato-magnesio', 'Glicinato de Magnesio', 'Cápsulas', 'Vitaminas', '', 'La forma más suave y biodisponible. Ideal para relajación y sueño.', 'sage', '', '[{"label":"60 caps","price":16800},{"label":"120 caps","price":16800}]'::jsonb, 16800, 4.9, 28, true, false, 9),
  ('glicinato-magnesio-polvo', 'Glicinato de Magnesio', 'Polvo', 'Vitaminas', '', 'Glicinato en polvo para mayor flexibilidad de dosis.', 'sage', '', '[{"label":"150 gr","price":12700},{"label":"300 gr","price":12700}]'::jsonb, 12700, 4.9, 14, true, false, 10),
  ('malato-magnesio', 'Malato de Magnesio', 'Cápsulas', 'Vitaminas', '', 'Energía mitocondrial y función muscular. Ideal para rendimiento físico.', 'sage', '', '[{"label":"60 caps","price":18600},{"label":"120 caps","price":18600}]'::jsonb, 18600, 4.8, 17, true, false, 11),
  ('malato-magnesio-polvo', 'Malato de Magnesio', 'Polvo', 'Vitaminas', '', 'Malato de magnesio en polvo. Fácil de incorporar a bebidas deportivas.', 'sage', '', '[{"label":"150 gr","price":12000},{"label":"300 gr","price":12000}]'::jsonb, 12000, 4.7, 11, true, false, 12),
  ('citrato-potasio', 'Citrato de Potasio', 'Cápsulas', 'Vitaminas', '', 'Equilibrio electrolítico, función muscular y cardiovascular. Alta absorción.', 'green', '', '[{"label":"60 caps","price":13500},{"label":"120 caps","price":13500}]'::jsonb, 13500, 4.7, 24, true, false, 13),
  ('citrato-potasio-polvo', 'Citrato de Potasio', 'Polvo', 'Vitaminas', '', 'Potasio en polvo soluble. Ideal para combinar con magnesio en bebidas.', 'green', '', '[{"label":"150 gr","price":6200},{"label":"300 gr","price":6200}]'::jsonb, 6200, 4.7, 16, true, false, 14),
  ('citrato-mg-k-polvo', 'Citrato Mg + K', 'Magnesio + Potasio — Polvo', 'Vitaminas', '', 'Fórmula combinada de citrato de magnesio y potasio. Electrolitos completos.', 'sage', '', '[{"label":"150 gr","price":7200},{"label":"300 gr","price":7200}]'::jsonb, 7200, 4.8, 20, true, false, 15),
  ('magnesio-potasio', 'Magnesio + Potasio', 'Cápsulas', 'Vitaminas', '', 'Dupla electrolítica para rendimiento, recuperación y calambres.', 'sage', '', '[{"label":"60 caps","price":14800},{"label":"120 caps","price":14800}]'::jsonb, 14800, 4.8, 35, true, false, 16),
  ('colageno', 'Colágeno', 'Hidrolizado Tipo I & III', 'Colágeno', '', 'Soporte para articulaciones, piel y tejido conectivo. Alta biodisponibilidad.', 'paper', '', '[{"label":"300 gr","price":12700},{"label":"500 gr","price":12700}]'::jsonb, 12700, 4.7, 66, true, true, 17),
  ('colageno-plus', 'Colágeno Plus', 'Con Vitamina C y Ácido Hialurónico', 'Colágeno', 'Premium', 'Fórmula potenciada: colágeno hidrolizado + vitamina C + ácido hialurónico.', 'paper', '', '[{"label":"300 gr","price":27000},{"label":"500 gr","price":27000}]'::jsonb, 27000, 4.8, 43, true, false, 18),
  ('espirulina', 'Espirulina', 'Spirulina platensis', 'Bienestar', '', 'Superalimento completo. Proteína, hierro, clorofila y antioxidantes naturales.', 'green', '', '[{"label":"60 caps","price":12699},{"label":"120 caps","price":12699}]'::jsonb, 12699, 4.8, 29, true, false, 19),
  ('curcuma', 'Cúrcuma', 'Curcumina + Piperina', 'Bienestar', '', 'Antiinflamatorio natural. La piperina potencia la absorción de curcumina hasta 20×.', 'navy', '', '[{"label":"60 caps","price":10500},{"label":"120 caps","price":10500}]'::jsonb, 10500, 4.8, 73, true, false, 20),
  ('maca', 'Maca', 'Lepidium meyenii', 'Bienestar', '', 'Adaptógeno andino. Vitalidad, energía sostenida y equilibrio hormonal natural.', 'sage', '', '[{"label":"60 caps","price":12900},{"label":"120 caps","price":12900}]'::jsonb, 12900, 4.7, 38, true, false, 21),
  ('ajo-vitamina-c', 'Ajo + Vitamina C', 'Extracto de ajo + ascorbato', 'Bienestar', '', 'Defensa inmunológica natural. Ajo deshidratado concentrado + vitamina C.', 'green', '', '[{"label":"60 caps","price":9300},{"label":"120 caps","price":9300}]'::jsonb, 9300, 4.7, 47, true, false, 22),
  ('cardo-mariano', 'Cardo Mariano', 'Silimarina 80%', 'Bienestar', '', 'Protección y regeneración hepática. Extracto estandarizado en silimarina 80%.', 'navy', '', '[{"label":"60 caps","price":13000},{"label":"120 caps","price":13000}]'::jsonb, 13000, 4.7, 52, true, false, 23),
  ('cartilago-tiburon', 'Cartílago de Tiburón', 'Condroitina natural', 'Articulaciones', '', 'Soporte articular natural. Rico en condroitina para movilidad y flexibilidad.', 'navy', '', '[{"label":"60 caps","price":15500},{"label":"120 caps","price":15500}]'::jsonb, 15500, 4.6, 61, true, false, 24),
  ('zeolita', 'Zeolita', 'Clinoptilolita activada', 'Bienestar', '', 'Desintoxicación celular y equilibrio del pH. Zeolita clínica de alta pureza.', 'navy', '', '[{"label":"60 caps","price":13950},{"label":"120 caps","price":13950}]'::jsonb, 13950, 4.7, 34, true, false, 25)
on conflict (id) do update set
  name = excluded.name, sub = excluded.sub, category = excluded.category,
  badge = excluded.badge, blurb = excluded.blurb, tone = excluded.tone,
  photo = excluded.photo, variants = excluded.variants, price = excluded.price,
  rating = excluded.rating, reviews = excluded.reviews,
  visible = excluded.visible, featured = excluded.featured, sort = excluded.sort;
